# Permalinks
#permalink:        pretty

# Theme
theme:            jekyll-theme-minimal

# Setup
title:            "DeltaX"
tagline:          Sissejuhatus R-i
url:              http://rkursus.github.io/
paginate:         1
baseurl:          /deltax
author:
  name:           Kaur Lumiste
  url:            
  email:          kaur.lumiste@ut.ee

# Custom vars
version:          1.0.0
github:
  repo:           http://rkursus.github.io/deltax

pages_list:       
  Praktikumid: '/praktikumid'
  